const constants = {
    //TODO: delete topic
    users: {
        CREATE_USER: 'CREATE_USER',
        ADD_USER: 'ADD_USER',
        ADD_USERS: 'ADD_USERS',
        ADD_LOGGED_IN_USER: 'ADD_LOGGED_IN_USER',
        SUBMIT_RESULT_OF_QUESTIONS_FOR_LOGGEDIN_USER: 'SUBMIT_RESULT_OF_QUESTIONS_FOR_LOGGEDIN_USER',
        ADD_RIGHT_ANSWERED_QUESTION_FOR_LOGGED_IN: 'ADD_RIGHT_ANSWERED_QUESTION_FOR_LOGGED_IN',
        ADD_WRONG_ANSWERED_QUESTION_FOR_LOGGED_IN: 'ADD_WRONG_ANSWERED_QUESTION_FOR_LOGGED_IN'
    },
    courses: {
        ADD_COURSE: 'ADD_COURSE',
        DELETE_COURSE: 'DELETE_COURSE',
        ADD_COURSES: 'ADD_COURSES',
        ADD_OWNER_TO_COURSE: 'ADD_OWNER_TO_COURSE',
        UPDATE_COURSE: 'UPDATE_COURSE'
    },
    lessons: {
        ADD_LESSON: 'ADD_LESSON',
        DELETE_LESSON: 'DELETE_LESSON',
        UPDATE_LESSON: 'UPDATE_LESSON',
        ADD_LESSONS: 'ADD_LESSONS'
    },
    topics: {
        ADD_TOPIC: 'ADD_TOPIC',
        ADD_TOPICS: 'ADD_TOPICS',
        ADD_TOPIC_QUESTIONS: 'ADD_TOPIC_QUESTIONS',
        UPDATE_TOPIC: 'UPDATE_TOPIC',
        DELETE_TOPIC: 'DELETE_TOPIC'
    },
    tests: {
        ADD_TEST: 'ADD_TEST',
        ADD_QUESTION_TO_TEST: 'ADD_QUESTION_TO_TEST'
    },
    questions: {
        ADD_QUESTION: 'ADD_QUESTION',
        DELETE_QUESTION: 'DELETE_QUESTION',
        ADD_QUESTIONS: 'ADD_QUESTIONS',
        UPDATE_QUESTION: 'UPDATE_QUESTION'
    },
    answers: {
        ADD_ANSWER: 'ADD_ANSWER',
        DELETE_ANSWER: 'DELETE_ANSWER',
        UPDATE_ANSWER: 'UPDATE_ANSWER',
        ADD_ANSWERS: 'ADD_ANSWERS'
    },
    mapping: {
        disciplineUser: {
            ADD_USERS_FOR_COURSE: 'ADD_USERS_FOR_COURSE'
        }
    }
}
export default constants
